### ISSUE TITLE
convert encrypted text to string

### ISSUE THREAD

**Issue by amirhossein-fzl** [keepsimple1/libaes#28]
How can I convert encrypt to string? I write the following code, it gives this error...

```rust
std::str::from_utf8(&encrypted[..])
```

error: 
`
Err(Utf8Error { valid_up_to: 0, error_len: Some(1) })
`

**Comment by keepsimple1** [comment]
By `encrypt` if you are referring to the [encryption](https://docs.rs/libaes/0.6.5/libaes/struct.Cipher.html#method.cbc_encrypt) functions of this crate, the output is `Vec<u8>` that might or might not be  a string.

**Comment by amirhossein-fzl** [comment]
> By `encrypt` if you are referring to the [encryption](https://docs.rs/libaes/0.6.5/libaes/struct.Cipher.html#method.cbc_encrypt) functions of this crate, the output is `Vec<u8>` that might or might not be a string.

So what's the point of this? When I can't store this password in the database, for example ...

**Comment by keepsimple1** [comment]
You can store binary bytes into most databases. Don't have to convert into a string.
